---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lukas.
--- DateTime: 11/08/2019 21:35
---

--- THIS ARE THE ELO'S FOR AN UPGRADE.
--- SO RANK 1 -> RANK 2 at 1400 elo
--- RANK 2 -> RANK 3 at 1600 etc
rank_1_upgrade  = 1400
rank_2_upgrade  = 1600
rank_3_upgrade  = 1800
rank_4_upgrade  = 2000

--- MORE CONFIGS AT:
-- strings.lua
-- duel/ft7/strings.lua


--- DONT TOUCH ANY OTHER FILES IF YOU DON'T KNOW WHAT YOU'RE DOING!
